### ISSUE TITLE
Include sub files in barrel file

### ISSUE THREAD

**Issue by maurice-b** [spiotr12/barrels-plugin#1]
Hi,

When I used this plugin, I was expecting that the barrel (index.ts) all sub typescript files includes. Is this a misconception? or do I have to do it manually?

**Comment by spiotr12** [comment]
Hi

Right now you have to do it manually. The way I do it is I have a live template `exp` and that gives me this piece of code `export * from '<cursor here>';` and pretty much I pick the file from the list.

Nevertheless that is interesting idea. I'll think about implementing it. Thanks!

PS sorry for late replay

**Comment by spiotr12** [comment]
Added these changes in version 1.7:
#2 Feature/file picker

Let me know when you try it if this is something you'd expect ;)
